/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ftp.project.a1;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPFile;
import org.apache.commons.net.ftp.FTPReply;
/**
 *
 * @author 12
 */
public class FTP_Client extends javax.swing.JFrame {

    /**
     * Creates new form FTP_Client
     */
    public FTP_Client() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connect");
        setAutoRequestFocus(false);

        jTextField1.setText("10.141.23.108");
        jTextField1.setToolTipText("");

        jLabel1.setText("IP");

        jLabel2.setText("PORT");

        jTextField2.setText("21");
        jTextField2.setToolTipText("");

        jButton1.setText("Connect");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên File", "Kiểu file", "Danh mục", "Ngày Upload", "Kích thước", "Người tạo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Download");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Upload");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reload");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ip = jTextField1.getText();
        String port = jTextField2.getText();
        
        if ("".equals(ip.trim())  ||  "".equals(port.trim()) ) {
            alterErorr("IP hoặc Port không được để trống");
            return;
        }
        
        JTextField username = new JTextField("ftp-user");
        JTextField pass = new JTextField("1234");
        JPanel panel = new JPanel(new GridLayout(0, 1));
       
        panel.add(new JLabel("Username"));
        panel.add(username);
        panel.add(new JLabel("Pasword"));
        panel.add(pass);
        panel.setVisible(true);
         
        
        int result = JOptionPane.showConfirmDialog(null, panel, "Đăng nhập",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            
            try {
                connect(ip, Integer.parseInt(port), username.getText(), pass.getText());
            } catch (Exception ex) {
                ex.printStackTrace();
                alterErorr(ex.getMessage());
            }
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            showListFile();
        } catch (IOException ex) {
            alterErorr("Lỗi hiển thị file");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         JPanel panel = new JPanel(new GridLayout(0, 1));
         int row = jTable1.getSelectedRow();
         
         if (jTable1.getSelectedRow() == -1) {
             alterErorr("Hãy chọn một tệp tin!");
             return;
         }
         
         final JFileChooser fileChooser = new JFileChooser();
         fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
         panel.add(fileChooser, BorderLayout.CENTER);

 
         String nameFile = jTable1.getValueAt(row, 0).toString();
         
         fileChooser.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
              if (e.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
                  fileChooser.getSelectedFile().getAbsolutePath();         
              }
           }
         });
         
       
        
        int result =  JOptionPane.showConfirmDialog(null, panel, "Chọn đường dẫn", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            try {
                downloadFile(DIRECTORY, nameFile, fileChooser.getSelectedFile().getAbsolutePath());
            } catch (Exception ex) {
                alterErorr("Chưa chọn đường dẫn lưu file!");
                ex.printStackTrace();
            }
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         final JFileChooser fileChooser = new JFileChooser();
         fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
         JPanel panel = new JPanel(new GridLayout(0, 1));
         panel.add(fileChooser, BorderLayout.CENTER);
 
         fileChooser.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
              if (e.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
                  fileChooser.getSelectedFile().getAbsolutePath();         
              }
           }
         });
         
         int result =  JOptionPane.showConfirmDialog(null, panel, "Chọn đường dẫn", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            try {
                uploadFile(fileChooser.getSelectedFile().getName().toString(), fileChooser.getSelectedFile().getCanonicalPath());
            } catch (Exception ex) {
                alterErorr("Chưa chọn đường dẫn lưu file!");
                ex.printStackTrace();
            }
        }  
    }//GEN-LAST:event_jButton3ActionPerformed
 
    private void downloadFile(String remotePath,String nameFile, String saveDir) {
         try {
               ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
               OutputStream outputStream1 = new BufferedOutputStream(new FileOutputStream(saveDir +"\\"+ nameFile));
               boolean success = ftpClient.retrieveFile(remotePath +"\\"+ nameFile, outputStream1);
               outputStream1.close();
               alterErorr("Tải thành công");
        } catch (Exception ex) {
               ex.printStackTrace();
               alterErorr("Tải file thất bại");
        } 

    }
    
      private void uploadFile(String nameFile, String saveDir) {
         try {
               File firstLocalFile = new File(saveDir);
 
     
               InputStream inputStream = new FileInputStream(firstLocalFile);

               System.out.println("Start uploading first file");
               boolean done = ftpClient.storeFile(nameFile, inputStream);
               inputStream.close();
               if (done) {
                   alterErorr("Tải file thành công");
                   showListFile();
               }
        } catch (Exception ex) {
               ex.printStackTrace();
               alterErorr("Tải file thất bại");
        } 

    }
    
    private void alterErorr(String mess) {
        JPanel panel = new JPanel(new GridLayout(0, 1));
        JLabel text = new JLabel(mess);
        panel.add(text);
        JOptionPane.showConfirmDialog(null, text, "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }
    
     private void connect(String host, int port, String username, String password) throws Exception {
        try {
            ftpClient.connect(host, port);
             int  replyCode = ftpClient.getReplyCode();
            if (!FTPReply.isPositiveCompletion(replyCode)) {
                throw new Exception("FTP serve refused connection.");
            }
 
            boolean logged = ftpClient.login(username, password);
            if (!logged) {
                // failed to login
                ftpClient.disconnect();
                throw new Exception("Could not login to the server.");
            }
            
            isLogin = true;
            ftpClient.enterLocalPassiveMode();
            showListFile();
            
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
        } catch (Exception ex) {
            throw new Exception("I/O error: "+ ex.getMessage());
        }
    }
    
    private void showListFile() throws IOException {
        if(!isLogin) return;
        FTPFile[] files1 = ftpClient.listFiles(DIRECTORY);
        printFileDetails(files1);
    }
    
     private void printFileDetails(FTPFile[] files) {
        DateFormat dateFormater = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        DefaultTableModel model = new DefaultTableModel();
        
        final String[] columns = new String[]{  "Tên File", "Kiểu file", "Danh mục", "Ngày Upload", "Kích thước", "Người tạo"};
        model.setColumnIdentifiers(columns);

        for (FTPFile file : files) {
            String nameFile = file.getName();
            if (file.isDirectory()) nameFile = "[" + nameFile + "]";
            double size = Math.ceil((double) file.getSize() / 1000);
            String timeCreate = dateFormater.format(file.getTimestamp().getTime());
            String category = DIRECTORY;
            String userCreate = file.getUser();
            String typeFile = getTypeFileByName(file, nameFile);
            
            model.addRow(new Object[]{nameFile, typeFile, category, timeCreate, size + " (kb)", userCreate});     
        }
        this.jTable1.setModel(model);
    }
     
    private String getTypeFileByName(FTPFile file, String nameFile) {
        if (file.isFile()) {
            return nameFile.substring(nameFile.length() - 4 , nameFile.length());
        }
        return "Directory";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    private FTPClient ftpClient = new FTPClient();
    private boolean isLogin = false;
    private static final String DIRECTORY = "/";
   
 

  
   
  
}
